In [18]:
import pandas as pd

Abrindo as bases

In [19]:
arquivo = 'MICRODADOS_CADASTRO_CURSOS_2012.CSV'
df_2012 = pd.read_csv(arquivo, encoding = 'latin-1', sep= ';')

In [20]:
arquivo2 = 'MICRODADOS_CADASTRO_CURSOS_2017.CSV'
df_2017 = pd.read_csv(arquivo2, encoding = 'latin-1', sep= ';')

C:\Users\FERNANDA\AppData\Local\Temp\ipykernel_16424\2621208775.py:2: DtypeWarning: Columns (1,3,4,6) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2017 = pd.read_csv(arquivo2, encoding = 'latin-1', sep= ';')

In [21]:
arquivo3 = 'MICRODADOS_CADASTRO_CURSOS_2022.CSV'
df_2022 = pd.read_csv(arquivo3, encoding = 'latin-1', sep= ';')

C:\Users\FERNANDA\AppData\Local\Temp\ipykernel_16424\1939690785.py:2: DtypeWarning: Columns (1,3,4,6) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2022 = pd.read_csv(arquivo3, encoding = 'latin-1', sep= ';')

2012 com colunas selecionadas

In [22]:
df2012_final = df_2012[['CO_IES', 'NU_ANO_CENSO', 'NO_UF', 'SG_UF', 'TP_ORGANIZACAO_ACADEMICA', 'TP_CATEGORIA_ADMINISTRATIVA', 'NO_CINE_AREA_GERAL', 'QT_VG_TOTAL', 'QT_INSCRITO_TOTAL', 'QT_ING', 'QT_ING_FEM', 'QT_ING_MASC', 'QT_ING_BRANCA', 'QT_ING_PRETA', 'QT_ING_PARDA', 'QT_ING_AMARELA', 'QT_ING_INDIGENA', 'QT_ING_CORND', 'QT_CONC', 'QT_CONC_MASC', 'QT_CONC_FEM', 'QT_CONC_BRANCA', 'QT_CONC_PRETA', 'QT_CONC_PARDA', 'QT_CONC_AMARELA', 'QT_CONC_INDIGENA', 'QT_CONC_CORND', 'QT_ING_DEFICIENTE', 'QT_CONC_DEFICIENTE']]
df2012_final

,CO_IES,NU_ANO_CENSO,NO_UF,SG_UF,TP_ORGANIZACAO_ACADEMICA,TP_CATEGORIA_ADMINISTRATIVA,NO_CINE_AREA_GERAL,QT_VG_TOTAL,QT_INSCRITO_TOTAL,QT_ING,...,QT_CONC_MASC,QT_CONC_FEM,QT_CONC_BRANCA,QT_CONC_PRETA,QT_CONC_PARDA,QT_CONC_AMARELA,QT_CONC_INDIGENA,QT_CONC_CORND,QT_ING_DEFICIENTE,QT_CONC_DEFICIENTE
0,699,2012,Rondônia,RO,1,1,"Engenharia, produção e construção",0.0,0.0,5.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,699,2012,Rondônia,RO,1,1,Educação,45.0,353.0,0.0,...,0.0,10.0,2.0,1.0,7.0,0.0,0.0,0.0,0.0,0.0
2,833,2012,Rondônia,RO,3,5,"Negócios, administração e direito",100.0,96.0,31.0,...,16.0,11.0,4.0,1.0,3.0,0.0,0.0,19.0,1.0,0.0
3,833,2012,Rondônia,RO,3,5,Educação,100.0,75.0,36.0,...,16.0,22.0,14.0,4.0,16.0,0.0,0.0,4.0,1.0,0.0
4,833,2012,Rondônia,RO,3,5,"Negócios, administração e direito",100.0,83.0,109.0,...,22.0,30.0,7.0,2.0,12.0,0.0,0.0,31.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63850,4504,2012,NaN,NaN,1,1,Educação,120.0,454.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63851,4724,2012,NaN,NaN,3,5,Educação,150.0,400.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63852,5403,2012,NaN,NaN,3,4,"Negócios, administração e direito",700.0,931.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63853,5403,2012,NaN,NaN,3,4,Educação,700.0,546.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63854,14724,2012,NaN,NaN,4,1,"Negócios, administração e direito",0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
df2012_final.isnull().sum()

CO_IES                             0
NU_ANO_CENSO                       0
NO_UF                           1151
SG_UF                           1151
TP_ORGANIZACAO_ACADEMICA           0
TP_CATEGORIA_ADMINISTRATIVA        0
NO_CINE_AREA_GERAL                 0
QT_VG_TOTAL                    31661
QT_INSCRITO_TOTAL              31661
QT_ING                          1151
QT_ING_FEM                      1151
QT_ING_MASC                     1151
QT_ING_BRANCA                   1151
QT_ING_PRETA                    1151
QT_ING_PARDA                    1151
QT_ING_AMARELA                  1151
QT_ING_INDIGENA                 1151
QT_ING_CORND                    1151
QT_CONC                         1151
QT_CONC_MASC                    1151
QT_CONC_FEM                     1151
QT_CONC_BRANCA                  1151
QT_CONC_PRETA                   1151
QT_CONC_PARDA                   1151
QT_CONC_AMARELA                 1151
QT_CONC_INDIGENA                1151
QT_CONC_CORND                   1151
QT_ING_DEFICIENTE               1151
QT_CONC_DEFICIENTE              1151
dtype: int64

In [24]:
df2012_limpa = df2012_final.dropna()
df2012_limpa

,CO_IES,NU_ANO_CENSO,NO_UF,SG_UF,TP_ORGANIZACAO_ACADEMICA,TP_CATEGORIA_ADMINISTRATIVA,NO_CINE_AREA_GERAL,QT_VG_TOTAL,QT_INSCRITO_TOTAL,QT_ING,...,QT_CONC_MASC,QT_CONC_FEM,QT_CONC_BRANCA,QT_CONC_PRETA,QT_CONC_PARDA,QT_CONC_AMARELA,QT_CONC_INDIGENA,QT_CONC_CORND,QT_ING_DEFICIENTE,QT_CONC_DEFICIENTE
0,699,2012,Rondônia,RO,1,1,"Engenharia, produção e construção",0.0,0.0,5.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,699,2012,Rondônia,RO,1,1,Educação,45.0,353.0,0.0,...,0.0,10.0,2.0,1.0,7.0,0.0,0.0,0.0,0.0,0.0
2,833,2012,Rondônia,RO,3,5,"Negócios, administração e direito",100.0,96.0,31.0,...,16.0,11.0,4.0,1.0,3.0,0.0,0.0,19.0,1.0,0.0
3,833,2012,Rondônia,RO,3,5,Educação,100.0,75.0,36.0,...,16.0,22.0,14.0,4.0,16.0,0.0,0.0,4.0,1.0,0.0
4,833,2012,Rondônia,RO,3,5,"Negócios, administração e direito",100.0,83.0,109.0,...,22.0,30.0,7.0,2.0,12.0,0.0,0.0,31.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31038,14408,2012,Distrito Federal,DF,4,1,"Agricultura, silvicultura, pesca e veterinária",90.0,1482.0,90.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0
31039,14408,2012,Distrito Federal,DF,4,1,Educação,80.0,72.0,69.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31040,14408,2012,Distrito Federal,DF,4,1,Educação,68.0,69.0,68.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31041,14408,2012,Distrito Federal,DF,4,1,"Negócios, administração e direito",45.0,44.0,39.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
31042,14408,2012,Distrito Federal,DF,4,1,Educação,160.0,209.0,207.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Seleção de colunas 2017

In [25]:
df2017_final = df_2017[['CO_IES', 'NU_ANO_CENSO', 'NO_UF', 'SG_UF', 'TP_ORGANIZACAO_ACADEMICA', 'TP_CATEGORIA_ADMINISTRATIVA', 'NO_CINE_AREA_GERAL', 'QT_VG_TOTAL', 'QT_INSCRITO_TOTAL', 'QT_ING', 'QT_ING_FEM', 'QT_ING_MASC', 'QT_ING_BRANCA', 'QT_ING_PRETA', 'QT_ING_PARDA', 'QT_ING_AMARELA', 'QT_ING_INDIGENA', 'QT_ING_CORND', 'QT_CONC', 'QT_CONC_MASC', 'QT_CONC_FEM', 'QT_CONC_BRANCA', 'QT_CONC_PRETA', 'QT_CONC_PARDA', 'QT_CONC_AMARELA', 'QT_CONC_INDIGENA', 'QT_CONC_CORND', 'QT_ING_DEFICIENTE', 'QT_CONC_DEFICIENTE']]
df2017_final

,CO_IES,NU_ANO_CENSO,NO_UF,SG_UF,TP_ORGANIZACAO_ACADEMICA,TP_CATEGORIA_ADMINISTRATIVA,NO_CINE_AREA_GERAL,QT_VG_TOTAL,QT_INSCRITO_TOTAL,QT_ING,...,QT_CONC_MASC,QT_CONC_FEM,QT_CONC_BRANCA,QT_CONC_PRETA,QT_CONC_PARDA,QT_CONC_AMARELA,QT_CONC_INDIGENA,QT_CONC_CORND,QT_ING_DEFICIENTE,QT_CONC_DEFICIENTE
0,699,2017,Rondônia,RO,1,1,"Engenharia, produção e construção",60.0,86.0,41.0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,699,2017,Rondônia,RO,1,1,Educação,50.0,160.0,45.0,...,9.0,35.0,6.0,21.0,17.0,0.0,0.0,0.0,0.0,0.0
2,833,2017,Rondônia,RO,3,5,Educação,390.0,461.0,19.0,...,10.0,9.0,0.0,1.0,2.0,0.0,0.0,16.0,0.0,0.0
3,833,2017,Rondônia,RO,3,5,Educação,300.0,399.0,1.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
4,833,2017,Rondônia,RO,3,5,Educação,300.0,399.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119793,673,2017,NaN,NaN,2,5,Educação,NaN,NaN,9.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
119794,673,2017,NaN,NaN,2,5,Educação,NaN,NaN,64.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
119795,673,2017,NaN,NaN,2,5,"Negócios, administração e direito",NaN,NaN,13.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
119796,673,2017,NaN,NaN,2,5,"Negócios, administração e direito",NaN,NaN,17.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
119797,673,2017,NaN,NaN,2,5,Artes e humanidades,NaN,NaN,18.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Exclusão de NaN 2017

In [26]:
df2017_limpa = df2017_final.dropna()
df2017_limpa

,CO_IES,NU_ANO_CENSO,NO_UF,SG_UF,TP_ORGANIZACAO_ACADEMICA,TP_CATEGORIA_ADMINISTRATIVA,NO_CINE_AREA_GERAL,QT_VG_TOTAL,QT_INSCRITO_TOTAL,QT_ING,...,QT_CONC_MASC,QT_CONC_FEM,QT_CONC_BRANCA,QT_CONC_PRETA,QT_CONC_PARDA,QT_CONC_AMARELA,QT_CONC_INDIGENA,QT_CONC_CORND,QT_ING_DEFICIENTE,QT_CONC_DEFICIENTE
0,699,2017,Rondônia,RO,1,1,"Engenharia, produção e construção",60.0,86.0,41.0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,699,2017,Rondônia,RO,1,1,Educação,50.0,160.0,45.0,...,9.0,35.0,6.0,21.0,17.0,0.0,0.0,0.0,0.0,0.0
2,833,2017,Rondônia,RO,3,5,Educação,390.0,461.0,19.0,...,10.0,9.0,0.0,1.0,2.0,0.0,0.0,16.0,0.0,0.0
3,833,2017,Rondônia,RO,3,5,Educação,300.0,399.0,1.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
4,833,2017,Rondônia,RO,3,5,Educação,300.0,399.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33576,19219,2017,Distrito Federal,DF,3,4,"Negócios, administração e direito",60.0,8.0,7.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
33577,19219,2017,Distrito Federal,DF,3,4,"Negócios, administração e direito",60.0,12.0,12.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
33578,19229,2017,Distrito Federal,DF,3,5,"Negócios, administração e direito",240.0,21.0,13.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
33579,19229,2017,Distrito Federal,DF,3,5,"Negócios, administração e direito",360.0,5.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
33580,19281,2017,Distrito Federal,DF,3,4,"Negócios, administração e direito",56.0,38.0,38.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [27]:
df2017_limpa.isnull().sum()

CO_IES                         0
NU_ANO_CENSO                   0
NO_UF                          0
SG_UF                          0
TP_ORGANIZACAO_ACADEMICA       0
TP_CATEGORIA_ADMINISTRATIVA    0
NO_CINE_AREA_GERAL             0
QT_VG_TOTAL                    0
QT_INSCRITO_TOTAL              0
QT_ING                         0
QT_ING_FEM                     0
QT_ING_MASC                    0
QT_ING_BRANCA                  0
QT_ING_PRETA                   0
QT_ING_PARDA                   0
QT_ING_AMARELA                 0
QT_ING_INDIGENA                0
QT_ING_CORND                   0
QT_CONC                        0
QT_CONC_MASC                   0
QT_CONC_FEM                    0
QT_CONC_BRANCA                 0
QT_CONC_PRETA                  0
QT_CONC_PARDA                  0
QT_CONC_AMARELA                0
QT_CONC_INDIGENA               0
QT_CONC_CORND                  0
QT_ING_DEFICIENTE              0
QT_CONC_DEFICIENTE             0
dtype: int64

Seleção de colunas 2022

In [28]:
df2022_final = df_2022[['CO_IES', 'NU_ANO_CENSO', 'NO_UF', 'SG_UF', 'TP_ORGANIZACAO_ACADEMICA', 'TP_CATEGORIA_ADMINISTRATIVA', 'NO_CINE_AREA_GERAL', 'QT_VG_TOTAL', 'QT_INSCRITO_TOTAL', 'QT_ING', 'QT_ING_FEM', 'QT_ING_MASC', 'QT_ING_BRANCA', 'QT_ING_PRETA', 'QT_ING_PARDA', 'QT_ING_AMARELA', 'QT_ING_INDIGENA', 'QT_ING_CORND', 'QT_CONC', 'QT_CONC_MASC', 'QT_CONC_FEM', 'QT_CONC_BRANCA', 'QT_CONC_PRETA', 'QT_CONC_PARDA', 'QT_CONC_AMARELA', 'QT_CONC_INDIGENA', 'QT_CONC_CORND', 'QT_ING_DEFICIENTE', 'QT_CONC_DEFICIENTE']]
df2022_final

,CO_IES,NU_ANO_CENSO,NO_UF,SG_UF,TP_ORGANIZACAO_ACADEMICA,TP_CATEGORIA_ADMINISTRATIVA,NO_CINE_AREA_GERAL,QT_VG_TOTAL,QT_INSCRITO_TOTAL,QT_ING,...,QT_CONC_MASC,QT_CONC_FEM,QT_CONC_BRANCA,QT_CONC_PRETA,QT_CONC_PARDA,QT_CONC_AMARELA,QT_CONC_INDIGENA,QT_CONC_CORND,QT_ING_DEFICIENTE,QT_CONC_DEFICIENTE
0,417,2022,NaN,NaN,1,4,Programas básicos,0,0,11,...,0,0,0,0,0,0,0,0,0,0
1,1,2022,NaN,NaN,1,1,"Negócios, administração e direito",150,198,0,...,0,0,0,0,0,0,0,0,0,0
2,1,2022,NaN,NaN,1,1,"Ciências naturais, matemática e estatística",850,552,0,...,0,0,0,0,0,0,0,0,0,0
3,1,2022,NaN,NaN,1,1,Educação,117,137,0,...,0,0,0,0,0,0,0,0,0,0
4,1,2022,NaN,NaN,1,1,Educação,121,128,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
573014,953,2022,Santa Catarina,SC,1,5,Computação e Tecnologias da Informação e Comun...,0,0,0,...,1,0,1,0,0,0,0,0,0,0
573015,953,2022,Santa Catarina,SC,1,5,"Negócios, administração e direito",0,0,0,...,0,0,0,0,0,0,0,0,0,0
573016,953,2022,Santa Catarina,SC,1,5,Educação,0,0,1,...,0,0,0,0,0,0,0,0,0,0
573017,953,2022,Santa Catarina,SC,1,5,Educação,0,0,0,...,3,0,3,0,0,0,0,0,0,0
573018,953,2022,Santa Catarina,SC,1,5,Educação,0,0,3,...,0,2,2,0,0,0,0,0,0,0

In [29]:
df2022_final.isnull().sum()

CO_IES                            0
NU_ANO_CENSO                      0
NO_UF                          9603
SG_UF                          9603
TP_ORGANIZACAO_ACADEMICA          0
TP_CATEGORIA_ADMINISTRATIVA       0
NO_CINE_AREA_GERAL                0
QT_VG_TOTAL                       0
QT_INSCRITO_TOTAL                 0
QT_ING                            0
QT_ING_FEM                        0
QT_ING_MASC                       0
QT_ING_BRANCA                     0
QT_ING_PRETA                      0
QT_ING_PARDA                      0
QT_ING_AMARELA                    0
QT_ING_INDIGENA                   0
QT_ING_CORND                      0
QT_CONC                           0
QT_CONC_MASC                      0
QT_CONC_FEM                       0
QT_CONC_BRANCA                    0
QT_CONC_PRETA                     0
QT_CONC_PARDA                     0
QT_CONC_AMARELA                   0
QT_CONC_INDIGENA                  0
QT_CONC_CORND                     0
QT_ING_DEFICIENTE                 0
QT_CONC_DEFICIENTE                0
dtype: int64

Exclusão NaN 2022

In [30]:
df2022_limpa = df2022_final.dropna()
df2022_limpa

,CO_IES,NU_ANO_CENSO,NO_UF,SG_UF,TP_ORGANIZACAO_ACADEMICA,TP_CATEGORIA_ADMINISTRATIVA,NO_CINE_AREA_GERAL,QT_VG_TOTAL,QT_INSCRITO_TOTAL,QT_ING,...,QT_CONC_MASC,QT_CONC_FEM,QT_CONC_BRANCA,QT_CONC_PRETA,QT_CONC_PARDA,QT_CONC_AMARELA,QT_CONC_INDIGENA,QT_CONC_CORND,QT_ING_DEFICIENTE,QT_CONC_DEFICIENTE
9603,2,2022,Distrito Federal,DF,1,1,Programas básicos,57,147,26,...,0,0,0,0,0,0,0,0,0,0
9604,2,2022,Distrito Federal,DF,1,1,Programas básicos,288,514,223,...,0,0,0,0,0,0,0,0,1,0
9605,2,2022,Distrito Federal,DF,1,1,Programas básicos,40,585,0,...,0,0,0,0,0,0,0,0,0,0
9606,2,2022,Distrito Federal,DF,1,1,Programas básicos,595,1577,482,...,0,0,0,0,0,0,0,0,2,0
9607,2,2022,Distrito Federal,DF,1,1,Programas básicos,132,167,53,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
573014,953,2022,Santa Catarina,SC,1,5,Computação e Tecnologias da Informação e Comun...,0,0,0,...,1,0,1,0,0,0,0,0,0,0
573015,953,2022,Santa Catarina,SC,1,5,"Negócios, administração e direito",0,0,0,...,0,0,0,0,0,0,0,0,0,0
573016,953,2022,Santa Catarina,SC,1,5,Educação,0,0,1,...,0,0,0,0,0,0,0,0,0,0
573017,953,2022,Santa Catarina,SC,1,5,Educação,0,0,0,...,3,0,3,0,0,0,0,0,0,0
573018,953,2022,Santa Catarina,SC,1,5,Educação,0,0,3,...,0,2,2,0,0,0,0,0,0,0

In [31]:
df2017_limpa.isnull().sum()

CO_IES                         0
NU_ANO_CENSO                   0
NO_UF                          0
SG_UF                          0
TP_ORGANIZACAO_ACADEMICA       0
TP_CATEGORIA_ADMINISTRATIVA    0
NO_CINE_AREA_GERAL             0
QT_VG_TOTAL                    0
QT_INSCRITO_TOTAL              0
QT_ING                         0
QT_ING_FEM                     0
QT_ING_MASC                    0
QT_ING_BRANCA                  0
QT_ING_PRETA                   0
QT_ING_PARDA                   0
QT_ING_AMARELA                 0
QT_ING_INDIGENA                0
QT_ING_CORND                   0
QT_CONC                        0
QT_CONC_MASC                   0
QT_CONC_FEM                    0
QT_CONC_BRANCA                 0
QT_CONC_PRETA                  0
QT_CONC_PARDA                  0
QT_CONC_AMARELA                0
QT_CONC_INDIGENA               0
QT_CONC_CORND                  0
QT_ING_DEFICIENTE              0
QT_CONC_DEFICIENTE             0
dtype: int64

Juntando as bases limpas

In [32]:
df_base_final = pd.concat([df2012_limpa, df2017_limpa, df2022_limpa], axis= 0)
df_base_final

,CO_IES,NU_ANO_CENSO,NO_UF,SG_UF,TP_ORGANIZACAO_ACADEMICA,TP_CATEGORIA_ADMINISTRATIVA,NO_CINE_AREA_GERAL,QT_VG_TOTAL,QT_INSCRITO_TOTAL,QT_ING,...,QT_CONC_MASC,QT_CONC_FEM,QT_CONC_BRANCA,QT_CONC_PRETA,QT_CONC_PARDA,QT_CONC_AMARELA,QT_CONC_INDIGENA,QT_CONC_CORND,QT_ING_DEFICIENTE,QT_CONC_DEFICIENTE
0,699,2012,Rondônia,RO,1,1,"Engenharia, produção e construção",0.0,0.0,5.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,699,2012,Rondônia,RO,1,1,Educação,45.0,353.0,0.0,...,0.0,10.0,2.0,1.0,7.0,0.0,0.0,0.0,0.0,0.0
2,833,2012,Rondônia,RO,3,5,"Negócios, administração e direito",100.0,96.0,31.0,...,16.0,11.0,4.0,1.0,3.0,0.0,0.0,19.0,1.0,0.0
3,833,2012,Rondônia,RO,3,5,Educação,100.0,75.0,36.0,...,16.0,22.0,14.0,4.0,16.0,0.0,0.0,4.0,1.0,0.0
4,833,2012,Rondônia,RO,3,5,"Negócios, administração e direito",100.0,83.0,109.0,...,22.0,30.0,7.0,2.0,12.0,0.0,0.0,31.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
573014,953,2022,Santa Catarina,SC,1,5,Computação e Tecnologias da Informação e Comun...,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
573015,953,2022,Santa Catarina,SC,1,5,"Negócios, administração e direito",0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
573016,953,2022,Santa Catarina,SC,1,5,Educação,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
573017,953,2022,Santa Catarina,SC,1,5,Educação,0.0,0.0,0.0,...,3.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
573018,953,2022,Santa Catarina,SC,1,5,Educação,0.0,0.0,3.0,...,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Salvando a base em CSV

In [33]:
df_base_final.to_csv('base_estudantes.csv', index= False)